"""Locations update

Revision ID: 63d11a472436
Revises: 0195a34dfae9
Create Date: 2026-08-18 01:13:44.488030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63d11a472436'
down_revision: Union[str, Sequence[str], None] = '0195a34dfae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('street', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('street_number', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('city', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('region', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('country', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'country')
    op.drop_column('locations', 'region')
    op.drop_column('locations', 'city')
    op.drop_column('locations', 'street_number')
    op.drop_column('locations', 'street')
    # ### end Alembic commands ###
