"""Changed speed to float

Revision ID: a32626b4c49a
Revises: 2a907a253920
Create Date: 2026-08-02 13:32:47.844810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a32626b4c49a'
down_revision: Union[str, Sequence[str], None] = '2a907a253920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("locations") as batch_op:
        batch_op.alter_column(
            "speed",
            existing_type=sa.INTEGER(),
            type_=sa.Float(),
            existing_nullable=True
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'speed',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
