"""Update location model

Revision ID: b76d27d65d9e
Revises: 048c87de6848
Create Date: 2026-08-20 23:11:22.052885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b76d27d65d9e'
down_revision: Union[str, Sequence[str], None] = '048c87de6848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('last_timestamp', sa.DateTime(timezone=True), nullable=False))
    op.add_column('locations', sa.Column('recorded', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'recorded')
    op.drop_column('locations', 'last_timestamp')
    # ### end Alembic commands ###
